version: '3.9'

services:
  discord-ollama:
    container_name: discord-ollama
    build:
      context: .
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DISCORD_GUILD_ID: ${DISCORD_GUILD_ID}
      OLLAMA_URL: ${OLLAMA_URL}
      OLLAMA_MODEL: ${OLLAMA_MODEL}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", $OLLAMA_URL]
      interval: 1m30s